# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Rbi5_59Wt1QWa9nEFZId9w2kQ9zNcvNc
"""

import pandas as pd
import matplotlib as plt
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import numpy as np
import math

#Lesen der Excel-Datei
df = pd.read_excel("program_info.xlsx")
df

#Runde die Werte sinnvoll auf volle 1000er Beträge.
df["max_bounty"] = round(df["max_bounty"], -3)
df["min_bounty"] = round(df["min_bounty"], -3)
df

#URL- und Namensspalte löschen, um ein Histogramm mit Max-Min Wert zu erstellen
df2 = df.drop(columns=['url', 'name'])
df2

#Historgram erstellen
fig = px.histogram(df, x=["min_bounty","max_bounty"], marginal="box")
fig.show()

#Histogramm mit spezifischem Bereich, um die Ausreißerwerte und die Werte zu beseitigen,
#denen wir 0 gegeben haben, weil sie keine Informationen enthalten

fig = px.histogram(df, x=["min_bounty","max_bounty"], marginal="box")
fig = fig.update_layout(xaxis_range=[50,10000])
fig.show()